{% set name = "optax" %}
{% set version = "0.2.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/optax-{{ version }}.tar.gz
  sha256: b2e38c7aea376186deae758ba7a258e6ef760c6f6131e9e11bc561c65386d594

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - absl-py >=0.7.1
    - chex >=0.1.86
    - jax >=0.4.27
    - jaxlib >=0.4.27
    - numpy >=1.18.0
    - typing_extensions >=3.10
    - etils

test:
  imports:
    - optax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    # Required by chex until it gets fixed upstream
    - setuptools

about:
  home: https://github.com/deepmind/optax
  summary: A gradient processing and optimisation library in JAX.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PhilipVinc
    - hbq1
